version: '3.8'  # Specify the Docker Compose version
services:
  ims-backend:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest  # Use the official MongoDB image
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Set the MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: password  # Set the MongoDB root password (change this for security)
    ports:
      - "27017:27017"
 
  mongo-express:
    image: mongo-express  # Use the official Mongo-Express image
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - "8081:8081"  # Map container port 8081 to host port 8081 (you can change the port number)
    depends_on:
      - mongodb  # Start Mongo-Express only after MongoDB is ready

